-module(m5_emu_api_tests).
-include_lib("eunit/include/eunit.hrl").

%% atomvm_m5_api.txt is generated by scripts/gen-atomvm-m5-api.sh from the pinned upstream revision.
every_upstream_function_is_exported_test() ->
    {ok, Bin} = file:read_file(api_file()),
    Lines = [L || L <- binary:split(Bin, <<"\n">>, [global]), L =/= <<>>],
    ?assert(length(Lines) > 200),
    ?assertEqual([], [L || L <- Lines, not exported(L)]).

api_file() ->
    {ok, Cwd} = file:get_cwd(),
    Candidates = [filename:join(Cwd, "test/atomvm_m5_api.txt"),
                  filename:join(code:lib_dir(m5_emu), "test/atomvm_m5_api.txt"),
                  filename:join([code:lib_dir(m5_emu), "..", "..", "..", "..", "test/atomvm_m5_api.txt"])],
    hd([F || F <- Candidates, filelib:is_regular(F)] ++ [hd(Candidates)]).

exported(Line) ->
    [M, FA] = binary:split(Line, <<":">>),
    [F, A] = binary:split(FA, <<"/">>),
    Mod = binary_to_atom(M, utf8),
    _ = code:ensure_loaded(Mod),
    erlang:function_exported(Mod, binary_to_atom(F, utf8), binary_to_integer(A)).
