import { writeFileSync } from "node:fs";
const url = "https://raw.githubusercontent.com/lovyan03/LovyanGFX/1.2.0/src/lgfx/Fonts/glcdfont.h";
const src = await (await fetch(url)).text();
const bytes = [...src.matchAll(/0x([0-9A-Fa-f]{2})/g)].map((m) => parseInt(m[1], 16));
if (bytes.length < 1280) throw new Error(`expected >= 1280 bytes, got ${bytes.length}`);
const table = bytes.slice(0, 1280);
const license = src.slice(0, src.indexOf("*/") + 2).split("\n").map((l) => "// " + l.replace(/^\/\*|\*\/$/g, "").trim()).join("\n");
writeFileSync(new URL("../web/src/font0.ts", import.meta.url),
`${license}
// Generated by scripts/import-font0.mjs from ${url}. Do not edit.
export const GLYPH_W = 5, CELL_W = 6, CELL_H = 8;
export const FONT0 = new Uint8Array([${table.join(",")}]);
`);
console.log("wrote web/src/font0.ts", table.length, "bytes");
